name: e2e
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e:
    permissions:
      packages: read
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci --audit=false
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: run app
      run: npm run serve &
      # todo: ^^ wait until app started

    - name: install browsers
      run: npx playwright install --with-deps

    - name: run tests
      run: npx playwright test

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e
        path: playwright-report/
        retention-days: 30
